### ISSUE TITLE
Special ID attribute in shortcode

### ISSUE THREAD

**Issue by dawixion** [brainstormforce/read-meter#51]
We recently used it in one of our projects and found one simple thing missing, namely, the ability to specify the post ID in the shortcode. So, we modified the code and are sending it to you to implement:

```php

/** YCDEVS MODE - ADD ID ATTR
 * Function of the read_meter shortcode.
 *
 * @since 1.0.0
 * @return shortcode display value.
 */
public function read_meter_shortcode($atts) {

	$atts = shortcode_atts( array(
		'id' => '',
	), $atts, 'read_meter' );

	$bsf_rt_post = '';

	if(isset($atts['id']) && !empty($atts['id'])){

		$bsf_rt_post = get_post($atts['id'])->ID;

	} else {

		$bsf_rt_post = get_the_ID($atts['id']);

	}

	$this->bsf_rt_calculate_reading_time( $bsf_rt_post, $this->bsf_rt_options );

	$label              = $this->bsf_rt_options['bsf_rt_reading_time_label'];
	$postfix            = $this->bsf_rt_options['bsf_rt_reading_time_postfix_label'];

	$shortcode_output = '<span class="bsf-rt-reading-time"><span class="bsf-rt-display-label" prefix="' . $label . '">
	</span> <span class="bsf-rt-display-time" reading_time="' . $this->reading_time . '"></span> 
	<span class="bsf-rt-display-postfix" postfix="' . $postfix . '"></span></span>';

	return $shortcode_output;
}
``` 

I believe this additional feature will be useful not only to us but also to a greater number of users 😉

**Comment by RajkiranBagal** [comment]
Hey @dawixion,

I am Rajkiran here from the Read Meter Development Team.

Can you please explain your usecase to us?

How this will be useful in your case?

This will help us understand the actual use of the attribute & then implement it too.

Looking forward to hearing from you.

**Comment by dawixion** [comment]
@RajkiranBagal - ye, why not ;) 

Case 1: Need to build a custom query, and loop item for custom view (Post image, Post title, Read Time, Link to post). 
Case 2: Need to show "similar posts" with read time (pretty the same case like first one).

This enhancement is mainly for developers, however, I am convinced that those who want to do more in the Gutenberg editor will gladly make use of the additional attribute.

You can check out my implementation of this code on the website: [Talent Days](https://talentdays.pl/blog/) (main page) and single post pages ;)

**Comment by RajkiranBagal** [comment]
Hey! @dawixion,

Thanks for the information & reference if was really helpful.

 We have implemented it here in this PR - https://github.com/brainstormforce/read-meter/pull/53/files

Please take a look & let us know your suggestions/thoughts.

Feel free to add those on the PR & if everything looks good then you can approve the PR too.

Looking forward to hearing from you.

**Comment by dawixion** [comment]
@RajkiranBagal Nice to know that improvements will be in the core ;)
